### ISSUE TITLE
How to use other methods to get proposals?

### ISSUE THREAD

**Issue by sunshineatnoon** [rbgirshick/fast-rcnn#50]
Instead of selective search, I want to use other methods to generate bounding box proposals. So what is the proper format I should use to feed the bounding boxes to the net when training it? Thanks!

**Comment by LarsHH** [comment]
If you just want to train on Pascal Voc 2007 you just go to /lib/datasets/pascal_voc and modify the _load_selective_search_roidb function

The proposals from your method should be in the same order as your ground-truth images. So for Pascal Voc this would be the order as in the list VOC2007/ImageSets/Main/train.txt

Then in _load_selective_search_roidb you load the proposals as a list of numpy arrays where each array represents the proposals for one image. The elements of the list should be the same order as the groundtruth like I said above

**Comment by sunshineatnoon** [comment]
@LarsHH Thanks for your reply. I acctually want to do some detection on imagenet 200 detection dataset, will it be possible to use the bounding box provided by rcnn?

**Comment by LarsHH** [comment]
I think fast r-cnn only provides selective search proposals for Pascal VOC 2007

If I'm right the ILSVRC 2014 Detection challenge has 40152 testing images?

You can try to find proposals for this on the internet. In a quick 1min search I didn't find anything but you may have more luck. Otherwise you would have to compute the bounding box proposals yourself. You can use selective search for that.

From my experience the selective_search_IJCV_for_python is very slow and crashes when you feed too many images into it. For me it took 1 day for 10000 images at ~2000 proposals per image with a script that feeds 300 images at a time. It also requires Matlab. You could check out dlib's selective search as in issue #51 which might be faster and more robust

Once you have the proposals you can go to tools/demo.py and modify it to use your images and proposals.

**Comment by sunshineatnoon** [comment]
@LarsHH Thanks, I am trying dlib's selective search now, I don't know if this implementation can give equal accuracy compared to the original selective search. I actually only interested in few categories in the imagenet detection database.

**Comment by sunshineatnoon** [comment]
@LarsHH If I want to change some code to use dlib's SS to generate bounding box for training, which files should I pay attention to?
