### ISSUE TITLE
IoU for negatives in fast-rcnn

### ISSUE THREAD

**Issue by nw362** [rbgirshick/fast-rcnn#99]
I  note that the paper [http://www.cs.berkeley.edu/~rbg/papers/pami/rcnn_pami.pdf] claims "We treat all region proposals with ≥ 0.5 IoU overlap with a ground-truth box as positives for that box’s class and the rest as negatives"
however config.py includes the following:
__C.TRAIN.BG_THRESH_LO = 0.1

Meaning that region proposals with < 0.1 IoU will not be used in the training. Is it that case that the results generated in the paper used this minimum threshold? Perhaps this is considered an implementation detail?

**Comment by rbgirshick** [comment]
@nw362 the paper you referenced is previous work. This paper is the correct one for this code: http://arxiv.org/pdf/1504.08083.pdf.

**Comment by nw362** [comment]
Thanks!

**Comment by chengmengli06** [comment]
How does this parameter affect performance? And how about using focal loss instead of this herustic?  I cannot find a reference for this herustic in Object Detection with Discriminatively Trained Part Based Models  and Spatial pyramid pooling.
After testing on RFCN using pascal voc dataset, this parameter is harmful to the final mAP, cause at least 2point lose.
